### ISSUE TITLE
Add proper e2e testing to the repository to ensure its components work

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-package-sigstore#14]
### Describe what should be investigated or refactored

Currently there isn't an easy way to test the sigstore stack without also deploying GitLab alongside it - once https://github.com/defenseunicorns/uds-package-sigstore/issues/3 is completed however we will have a way to easily test with only Keycloak (which is part of `uds-core`)

### Links to any relevant code

https://github.com/defenseunicorns/uds-package-sigstore/blob/main/src/fulcio/values/values.yaml#L23

### Additional context

This will also require changes to `uds-core` to support this properly: https://github.com/defenseunicorns/uds-core/issues/509

**Comment by oates** [comment]
this is complete as of 4 Nov 24
